version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  players-api:
    build: .
    ports:
      - "8112:8112"
    env_file:
      - .env
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    command: [ "./playersApiApp" ]
