openapi: 3.0.0
info:
  description: "Public documentation for players api"
  version: "0.0.1"
  title: "Players Api"
paths:
  /players/{playerId}:
    get:
      summary: "Return players"
      operationId: "getPlayers"
      parameters:
        - in: path
          name: playerId
          required: true
          schema:
            type: string
          description: Player id
      responses:
        "200":
          description: "successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
        "400":
          description: "bad request"
        "404":
          description: "player not found"
  /players:
    get:
      summary: "Get players for a given team"
      operationId: "getSquad"
      parameters:
        - in: query
          name: teamId
          required: true
          schema:
            type: integer
          description: Squad
      responses:
        "200":
          description: "successful"
        "400":
          description: "bad request"
        "404":
          description: "player not found"

components:
  schemas:
    Player:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        firstname:
          type: "string"
    ApiResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        type:
          type: "string"
        message:
          type: "string"
